repos:
# Permet de générer / mettre à jour le fichier requirements.txt avant chaque commit
# Equivalent à la commande 'uv pip compile pyproject.toml -o requirements.txt'
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.11.25
  hooks:
  # Run the pip compile
    - id: pip-compile
      args: [pyproject.toml, -o, requirements.txt]