name: Intégration continue

on:
    push:
        branches:
            - 'feature/*'
            - 'docs/*'
    pull_request:
        branches:
            - develop
            - release
            - main

jobs:
    analyse-et-tests:
        runs-on: ubuntu-latest

        steps:
        - name: Vérification code
          uses: actions/checkout@v7

        - name: Installation Python
          uses: actions/setup-python@v6
          with:
            python-version: '3.14'
            cache: 'pip'
            
        - name: Installation dépendances
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest ruff

        - name: Lint avec Ruff
          run: ruff check .

        - name:  Exécuter tests avec Pytest
          run: |
            pytest tests/
          env:
            PYTHONPATH: .
